In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Train_dataset = pd.read_csv('C:\\TD\\Sem 1\\Courses\\Machine Learning\\train.csv')
X_train= Train_dataset.iloc[:, :-1].values
Y_train = Train_dataset.iloc[:, -1].values

Test_dataset = pd.read_csv('C:\\TD\\Sem 1\\Courses\\Machine Learning\\test.csv')
X_test = Test_dataset.iloc[:, 1:].values


In [3]:
len(X_train)

889

In [4]:
len(Y_train)

889

In [5]:
len(X_test)

418

In [6]:
print(X_train)

[[3 'male' 'S' 22.0]
 [1 'female' 'C' 38.0]
 [3 'female' 'S' 26.0]
 ...
 [3 'female' 'S' 23.74]
 [1 'male' 'C' 26.0]
 [3 'male' 'Q' 32.0]]


In [7]:
print(X_test)

[[3 'male' 34.5 'Q']
 [3 'female' 47.0 'S']
 [2 'male' 62.0 'Q']
 ...
 [3 'male' 38.5 'S']
 [3 'male' 24.04 'S']
 [3 'male' 24.04 'C']]


In [8]:
Y_train = Y_train.reshape(len(Y_train),1)

In [9]:
print(Y_train)

[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]


In [10]:
# Feature scaling for age in training set and test set
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:4] = sc.fit_transform(X_train[:, 3:4])


In [11]:
X_test[:,2:3] = sc.transform(X_test[:, 2:3])

In [12]:
print(X_train)

[[3 'male' 'S' -0.49090521724461167]
 [1 'female' 'C' 0.7236457703078705]
 [3 'female' 'S' -0.18726747035649113]
 ...
 [3 'female' 'S' -0.3588227973482794]
 [1 'male' 'C' -0.18726747035649113]
 [3 'male' 'Q' 0.2681891499756897]]


In [13]:
print(X_test)

[[3 'male' 0.457962741780765 'Q']
 [3 'female' 1.4068307008061418 'S']
 [2 'male' 2.545472251636594 'Q']
 ...
 [3 'male' 0.7616004886688856 'S']
 [3 'male' -0.3360499663316703 'S']
 [3 'male' -0.3360499663316703 'C']]


In [14]:
#Encoding for sex for training set
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train[:,1]= le.fit_transform(X_train[:,1])



In [15]:
X_train

array([[3, 1, 'S', -0.49090521724461167],
       [1, 0, 'C', 0.7236457703078705],
       [3, 0, 'S', -0.18726747035649113],
       ...,
       [3, 0, 'S', -0.3588227973482794],
       [1, 1, 'C', -0.18726747035649113],
       [3, 1, 'Q', 0.2681891499756897]], dtype=object)

In [16]:
#Encoding for Embarked(S/C/Q) for training set
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))


In [17]:
X_train

array([[0.0, 0.0, 1.0, 3, 1, -0.49090521724461167],
       [1.0, 0.0, 0.0, 1, 0, 0.7236457703078705],
       [0.0, 0.0, 1.0, 3, 0, -0.18726747035649113],
       ...,
       [0.0, 0.0, 1.0, 3, 0, -0.3588227973482794],
       [1.0, 0.0, 0.0, 1, 1, -0.18726747035649113],
       [0.0, 1.0, 0.0, 3, 1, 0.2681891499756897]], dtype=object)

In [18]:
#Encoding for sex for test set
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_test[:,1]= le.fit_transform(X_test[:,1])

In [19]:
print(X_test)

[[3 1 0.457962741780765 'Q']
 [3 0 1.4068307008061418 'S']
 [2 1 2.545472251636594 'Q']
 ...
 [3 1 0.7616004886688856 'S']
 [3 1 -0.3360499663316703 'S']
 [3 1 -0.3360499663316703 'C']]


In [20]:
#Encoding for Embarked(S/C/Q) for test set
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X_test = np.array(ct.fit_transform(X_test))

In [21]:
print(X_test)

[[0.0 1.0 0.0 3 1 0.457962741780765]
 [0.0 0.0 1.0 3 0 1.4068307008061418]
 [0.0 1.0 0.0 2 1 2.545472251636594]
 ...
 [0.0 0.0 1.0 3 1 0.7616004886688856]
 [0.0 0.0 1.0 3 1 -0.3360499663316703]
 [1.0 0.0 0.0 3 1 -0.3360499663316703]]


In [22]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, Y_train)

C:\Users\surab\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression(random_state=0)

In [23]:
print(classifier.predict([[0.0, 0.0, 1.0, 3, 1,sc.transform([[22]])]]))

[0]


C:\Users\surab\anaconda3\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [24]:
print(classifier.predict([[1.0, 0.0, 0.0, 1, 0,sc.transform([[38]])]]))

[1]


C:\Users\surab\anaconda3\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [25]:
y_pred = classifier.predict(X_test)
print(y_pred)

[0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1
 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1
 1 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 1 1 0 1
 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0
 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0
 0 1 1 1 1 1 0 1 0 0 0]


In [27]:
X_test_1 = Test_dataset.iloc[:, 0:1].values
print(X_test_1)


[[ 892]
 [ 893]
 [ 894]
 [ 895]
 [ 896]
 [ 897]
 [ 898]
 [ 899]
 [ 900]
 [ 901]
 [ 902]
 [ 903]
 [ 904]
 [ 905]
 [ 906]
 [ 907]
 [ 908]
 [ 909]
 [ 910]
 [ 911]
 [ 912]
 [ 913]
 [ 914]
 [ 915]
 [ 916]
 [ 917]
 [ 918]
 [ 919]
 [ 920]
 [ 921]
 [ 922]
 [ 923]
 [ 924]
 [ 925]
 [ 926]
 [ 927]
 [ 928]
 [ 929]
 [ 930]
 [ 931]
 [ 932]
 [ 933]
 [ 934]
 [ 935]
 [ 936]
 [ 937]
 [ 938]
 [ 939]
 [ 940]
 [ 941]
 [ 942]
 [ 943]
 [ 944]
 [ 945]
 [ 946]
 [ 947]
 [ 948]
 [ 949]
 [ 950]
 [ 951]
 [ 952]
 [ 953]
 [ 954]
 [ 955]
 [ 956]
 [ 957]
 [ 958]
 [ 959]
 [ 960]
 [ 961]
 [ 962]
 [ 963]
 [ 964]
 [ 965]
 [ 966]
 [ 967]
 [ 968]
 [ 969]
 [ 970]
 [ 971]
 [ 972]
 [ 973]
 [ 974]
 [ 975]
 [ 976]
 [ 977]
 [ 978]
 [ 979]
 [ 980]
 [ 981]
 [ 982]
 [ 983]
 [ 984]
 [ 985]
 [ 986]
 [ 987]
 [ 988]
 [ 989]
 [ 990]
 [ 991]
 [ 992]
 [ 993]
 [ 994]
 [ 995]
 [ 996]
 [ 997]
 [ 998]
 [ 999]
 [1000]
 [1001]
 [1002]
 [1003]
 [1004]
 [1005]
 [1006]
 [1007]
 [1008]
 [1009]
 [1010]
 [1011]
 [1012]
 [1013]
 [1014]
 [1015]
 [1016]


In [28]:
Output=np.concatenate((X_test_1.reshape(len(X_test_1),1),y_pred.reshape(len(y_pred),1)),1)

In [29]:
print(Output)

[[ 892    0]
 [ 893    0]
 [ 894    0]
 [ 895    0]
 [ 896    1]
 [ 897    0]
 [ 898    1]
 [ 899    0]
 [ 900    1]
 [ 901    0]
 [ 902    0]
 [ 903    0]
 [ 904    1]
 [ 905    0]
 [ 906    1]
 [ 907    1]
 [ 908    0]
 [ 909    0]
 [ 910    1]
 [ 911    1]
 [ 912    0]
 [ 913    0]
 [ 914    1]
 [ 915    1]
 [ 916    1]
 [ 917    0]
 [ 918    1]
 [ 919    0]
 [ 920    0]
 [ 921    0]
 [ 922    0]
 [ 923    0]
 [ 924    0]
 [ 925    1]
 [ 926    1]
 [ 927    0]
 [ 928    1]
 [ 929    1]
 [ 930    0]
 [ 931    0]
 [ 932    0]
 [ 933    0]
 [ 934    0]
 [ 935    1]
 [ 936    1]
 [ 937    0]
 [ 938    0]
 [ 939    0]
 [ 940    1]
 [ 941    0]
 [ 942    0]
 [ 943    0]
 [ 944    1]
 [ 945    1]
 [ 946    0]
 [ 947    0]
 [ 948    0]
 [ 949    0]
 [ 950    0]
 [ 951    1]
 [ 952    0]
 [ 953    0]
 [ 954    0]
 [ 955    1]
 [ 956    1]
 [ 957    1]
 [ 958    1]
 [ 959    0]
 [ 960    1]
 [ 961    1]
 [ 962    1]
 [ 963    0]
 [ 964    1]
 [ 965    1]
 [ 966    1]
 [ 967    1]
 [ 968    0]